### ISSUE TITLE
In the README, change the x-axis label from "number of tasks" to "number of concurrent threads"

### ISSUE THREAD

**Issue by DeflateAwning** [caitaozhan/stress#4]
The current label "number of tasks" doesn't really make sense. Assuming I got the right idea, changing the axis label makes way more sense.

**Comment by caitaozhan** [comment]
Thanks for your comment. I updated it to "number of concurrent tasks".

"concurrent threads" is not accurate either. It is actually "concurrent process" and each process is dealing with a task.

**Comment by caitaozhan** [comment]
updated.
